---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: rhel8
    image: docker.io/timkids/docker-rhel8-java-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true

  - name: ubuntu2004
    image: docker.io/timkids/docker-ubuntu2004-java-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true

  - name: debian10
    image: docker.io/timkids/docker-debian10-java-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
