---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: rhel8
    image: timkids/docker-rhel8-java-ansible
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

  - name: ubuntu2004
    image: timkids/docker-ubuntu2004-java-ansible
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

  - name: debian10
    image: timkids/docker-debian10-java-ansible
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
