---

- name: Prepare
  hosts: all
  tasks:
    - name: "Include vars depends on OS"
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_distribution }}.yml'
            - '{{ ansible_os_family }}.yml'
            - default.yml
          paths:
            - 'vars'

    - name: "Install java"
      package:
        name: "{{ prepare_packages }}"
        update_cache: true
