---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Group check
    ansible.builtin.group:
      name: "tomcat"
    check_mode: true
    register: __group_result

  - name: User check
    ansible.builtin.user:
      name: "tomcat"
    check_mode: true
    register: __user_result

  - name: Service check
    ansible.builtin.service_facts:
    check_mode: true

  - name: "Check the tomcat default page"
    ansible.builtin.uri:
      url: "http://localhost:8080"
      return_content: true
    register: __tomcat_uri_result
    failed_when:
      - __tomcat_uri_result.content != "Please select an application by adding the context URL.\n"

  - name: "Check the user that runs the process"
    command: ps -o pid= -o cmd= -u tomcat
    register: __process_user_result
    changed_when: false

  - name: "Assert tests results"
    ansible.builtin.assert:
      that:
        - not __group_result.changed
        - not __user_result.changed
        - ansible_facts.services['tomcat.service'] is defined
        - ansible_facts.services['tomcat.service']['status'] == "enabled"
        - ansible_facts.services['tomcat.service']['state'] == "running"
        - __process_user_result.stdout_lines | length > 0
        - '"tomcat-tomcat" in __process_user_result.stdout'
