---

# Set a custom java home if needed
# Default value for os are stored in vars dir
# java_home:

# System/group user to launch tomcat
tomcat_sys_user: tomcat
tomcat_sys_group: tomcat

tomcat_version: "10.0.13"

# Download configurations
tomcat_download_url: "https://archive.apache.org/dist/tomcat/\
  tomcat-{{ __tomcat_major_version }}/\
  v{{ tomcat_version }}/bin/\
  apache-tomcat-{{ tomcat_version }}.tar.gz"
tomcat_download_checksum_type: "sha512"
tomcat_download_checksum: "https://archive.apache.org/dist/tomcat/\
  tomcat-{{ __tomcat_major_version }}/\
  v{{ tomcat_version }}/bin/\
  apache-tomcat-{{ tomcat_version }}.tar.gz.{{ tomcat_download_checksum_type }}"

# tomcat_download_username:
# tomcat_download_password:

tomcat_archive_path: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

tomcat_installation_path: "/opt/tomcat-{{ tomcat_sys_user }}"
tomcat_force_unarchive: false

# Set to true if you want to delete the archive
# Be carreful this will make the role non-idempotent
tomcat_delete_archive: false
