---

- name: "Configure tomcat server.xml"
  ansible.builtin.template:
    src: server.xml.j2
    dest: "{{ tomcat_installation_path }}/conf/server.xml"
    owner: "{{ tomcat_sys_user }}"
    group: "{{ tomcat_sys_group }}"
    mode: "0644"
  notify:
    - "Restart tomcat"

- name: "Configure environment vars for tomcat"
  ansible.builtin.template:
    src: setenv.sh.j2
    dest: "{{ tomcat_installation_path }}/bin/setenv.sh"
    owner: "{{ tomcat_sys_user }}"
    group: "{{ tomcat_sys_group }}"
    mode: "0644"
  notify:
    - "Restart tomcat"

- name: "Replace the default page"
  ansible.builtin.copy:
    content: |
      Please select an application by adding the context URL.
    dest: "{{ tomcat_installation_path }}/webapps/ROOT/index.html"
    owner: "{{ tomcat_sys_user }}"
    group: "{{ tomcat_sys_group }}"
    mode: "0640"
  notify:
    - "Restart tomcat"
