---

- name: "Configure systemd"
  ansible.builtin.template:
    src: systemd/tomcat_service.service.j2
    dest: "{{ tomcat_systemd_service_file_path }}"
    mode: 0644
    owner: root
    group: root
  notify: "Reload and restart tomcat systemd service"
